### ISSUE TITLE
Building on Linux?

### ISSUE THREAD

**Issue by Phantop** [Razor12911/xtool#4]
This seems to be written specifically with Delphi and non-Linux platforms in mind. Is there any way to possibly build this with e.g. FreePascal on Linux (or perhaps any intention to make that a working possibility)?

**Comment by Razor12911** [comment]
I'm not familiar with the Linux platform however a port is possible with limitations of some features.

**Comment by jclsn** [comment]
@Razor12911 What features? 

The thing is unpacking games fails sometimes using Wine emulator on Linux. So it would be nice if there were a native unpacker. I see there are some DLLs included also, so I guess it is not trivial to port.

**Comment by Razor12911** [comment]
It's the very same DLLs that could be the cause of most if not all the issues and porting them may not be possible as some of them are not open source. Perhaps if you were to outline what games fail to unpack then I may come up a solution to the issues you are facing.

**Comment by jclsn** [comment]
Well, I won't name any games publicly here. It is usually some memory errors though. I also gave up using these repacks for the same reason.

**Comment by Razor12911** [comment]
Well unfortunately I cannot help you if there are no examples or producible samples where xtool fails and at times, it's the repackers themselves who could be misusing xtool, too many variables to consider. Does the xtool here on github releases work at all when you use it on your environment?

**Comment by jclsn** [comment]
Well, I can name you Forza Horizon 5 and Assassin's Creed Valhalla from Fitigirl, since I have bought these games recently and there should be no issue.

I think the tool itself should work. I had some successes with other games. There might be some DLLs or registry values missing in the Lutris Wine prefix I have tried. To test this you would have to install Linux (preferably Manjaro or Ubuntu, since they should work out of the box) and Lutris. In Lutris you can install games and try to execute the repacks. There are ways to install missing DLLs with winetricks.

I wouldn't know how to test you xtool Github release with those repacks. Actually I am just assuming that this is the right tool to use, because research online suggested it is. Maybe Fitgirl uses some completely different though!
