### ISSUE TITLE
I can't use it

### ISSUE THREAD

**Issue by ahmed329** [Razor12911/xtool#5]
In output option it shows me a file or none and if I choose file I have to choose an existing file and the compressed output would be that file is that how it should work and how to decompress that and it many times shows 128 MB in memory but I have 16 GB ram and I didn't check low memory box and do I have to choose methods or leave it blank

**Comment by Razor12911** [comment]
Hi. The output file must be a non existing file as this is the new file that xtool will generate. You also need to have some prior knowledge of the files you've set as your input, are they zip files? if they are then your method should be zlib as this is mostly the compression method used on them. The idea behind xtool is to improve compression on files that have been compressed already (typically with weak compression), it reverses this to giving you an opportunity of applying stronger compression of your choice.

**Comment by ahmed329** [comment]
but where is the output file I can't see away to choose the location of the new file

**Comment by Razor12911** [comment]
the syntax of xtool via cli is as follows xtool.exe precomp [parameters] [input] **[output]**

when using gui version of xtool, the output can be set by first changing it to a file then use the search button (it has the magnifier icon), set filename on the save dialog then click on save. Be mindful of the directory where you're saving the file and expect it to appear there

**Comment by hamomagdy724** [comment]
bro i do not understand you ... i want the compressed zip file with xtool to become again a zip file not another extension of xtool output ... how can i do that .... in the output it appears NONE or FILE only not a zip file choice as a choice

what i do is:
put in the input the xtool compressed file
choosing zlib in configure
in the output , neither NONE nor FILE choices give me a zip file output ..... i hope you understand me thank you

**Comment by Razor12911** [comment]
@hamomagdy724 Hi, your question went under the radar because it was posted in a thread meant to resolve another issue but to answer your question. This program isn't a recompressor but a precompressor, there's a difference in the sense that a recompressor makes the file usable after its being processed, so files like zip archives should be extractable and png images should be viewable after being processed with the key difference being either recompressed either for the best size or for speed however, a precompressor works differently in the sense that the file cannot be used directly anymore after being processed simply because the main idea behind this technique is to alter the data in such a way that when a lossless compressor is used you achieve after better results.

A simple example is having a zip file sized 2GB, when you try to compress this file using lzma it becomes 1.9GB, what xtool will do is extract this zip file first then feed the precompressed file to lzma to get an even better result, e.g. 800MB.

This process is also reversible, when you require the original zip file, lzma decompresses the precompressed file then xtool gives you back the 80MB. The program is meant for archival purposes where the user tries to reduce the space taken up by their files and retrieve them in their original state when they need them.
